### ISSUE TITLE
Feature Request: Release

### ISSUE THREAD

**Issue by jgarte** [useblocks/sphinx-collections#14]
Hi,

Is there a plan to release `0.0.1` as mentioned in the [changelog](https://github.com/useblocks/sphinx-collections/blob/master/docs/changelog.rst)?

**Comment by jgarte** [comment]
I see that there is a version mismatch in the [setup.py.](https://github.com/useblocks/sphinx-collections/blob/master/setup.py#L11)

Should that be updated? How should we keep those versions in sync going forward?

**Comment by marcel-cw** [comment]
+1, need a new release version with the bugfixes on master also.

**Comment by danwos** [comment]
Wow, the second release, 4 years later :)
Thanks for putting pressure on this :+1: 

New release version is `0.2.0`.

**Comment by marcel-cw** [comment]
@danwos
Hi Daniel,
Thanks for the new release version!!!
Unfortunately I cannot update to this version, there is something wrong I guess.
I have create a new issue https://github.com/useblocks/sphinx-collections/issues/26
