### ISSUE TITLE
How to build with Sphinx Collections?

### ISSUE THREAD

**Issue by anugrahjo** [useblocks/sphinx-collections#17]
Is there an example package where 'Sphinx Collections' is used? Inside `conf.py`, I set 'collections' with a dict for copying a folder but it doesn't seem to do anything during the build. Should I add `sphinx_collections` to the list of extensions in `conf.py`? In general, what changes should I make on my original repository to use 'Sphinx Collections'?

**Comment by jgarte** [comment]
@anugrahjo Hi, can you share the project repository that you are working on?

Yes, you should be adding `sphinx.collections` to your `conf.py` file similar to [here](https://github.com/useblocks/sphinx-collections/blob/master/tests/doc_test/config_string/conf.py#L3).

**Comment by anugrahjo** [comment]
Hi @jgarte,

I see, thanks. It should be `sphinx_contrib.collections` by the way. I have tried all possible names for the extension before raising this issue. It would be nice to add it to the Introduction in the documentation. Everything else was pretty clear in the docs, but the extension name to be used in `conf.py` couldn't be found anywhere. 

I am working on template repository for documentation and testing for my lab. It does not do much. Do you still need it?

**Comment by jgarte** [comment]
@danwos 

See @anugrahjo 's comment regarding `sphinxcontrib.collections`. What do you think?

> I am working on template repository for documentation and testing for my lab. It does not do much. Do you still need it?

If you end up finishing the example feel free to share it. Any examples of how people are using `sphinx-collections` would be great.

**Comment by anugrahjo** [comment]
@jgarte 
Sure, once the documentation template is final, I will share it here.
